CREATE TABLE TB_STUDENT(
	STD_NO NUMBER,
	STD_NAME VARCHAR2(20),
	STD_AGE NUMBER,
	STD_GENDER CHAR(1),
	STD_SCORE CHAR(1)
);

ALTER TABLE TB_STUDENT
ADD CONSTRAINT TB_STUDENT_PK PRIMARY KEY(STD_NO);

ALTER TABLE TB_STUDENT
MODIFY STD_NAME VARCHAR2(20) CONSTRAINT STD_NAME_NN NOT NULL;

ALTER TABLE TB_STUDENT
MODIFY STD_AGE NUMBER CONSTRAINT STD_AGE NOT NULL;

ALTER TABLE TB_STUDENT
ADD CONSTRAINT STD_GENDER 
CHECK(STD_GENDER IN ('M', 'F') );

ALTER TABLE TB_STUDENT
ADD CONSTRAINT STD_SCORE 
CHECK(STD_SCORE IN ('A', 'B', 'C', 'D','F') );

COMMENT ON COLUMN TB_STUDENT.STD_NO IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.STD_NAME IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STD_AGE IS '학생 나이';
COMMENT ON COLUMN TB_STUDENT.STD_GENDER IS '학생 성별';
COMMENT ON COLUMN TB_STUDENT.STD_SCORE IS '학생 성적';

CREATE SEQUENCE SEQ_STD_NO NOCACHE;


INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '홍길동', '20', 'M', 'A');

INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '이길동', '21', 'F', 'B');

INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '삼길동', '22', 'M', 'C');

INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '사길동', '23', 'F', 'D');

INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '오길동', '24', 'M', 'F');

INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '육길동', '25', 'F', 'A');

COMMIT;


SELECT * FROM TB_STUDENT
ORDER BY STD_NO;

ROLLBACK;

select SEQ_STD_NO.nextval from dual;

alter sequence SEQ_STD_NO increment BY 1;

DELETE FROM TB_STUDENT 
WHERE STD_NO > 1;

